debug: make mappings buffer-local
kernel-panic96/vim-go pull request #1
Opened 2020-10-12 02:53 UTC by bhcleek

Make debug mappings buffer-local and move debug_mode.vim into debug.vim.

This will leave the debug mappings in place in all buffers to which they are applied when the filetype is set, but that's a long-standing issue that can be solved separately; I'll submit a separate pull request against master after this changes are merged into master.

##### use execute() instead of normal mode command

##### Use the usual vim-go script header and footer

Move the modeline to the end of the file and add expandtab.

Add the usual header for vim-go.

##### doc: update docs for g:go_debug_mappings

Update docs for g:go_debug_mappings to reflect the desired state.

##### debug: refactor debug mapping handling

Refactor debug mapping to be normal mode buffer-local mappings only.

Restore mappings in go#debug#Stop instead of s:stop() for consistency of
purpose.

##### debug: fix unmapping of debugging mappings

Fix unmapping of a long-standing unreported bug where the debugging
mappings were not being unmapped when debugging stops.

##### debug: move mapping functions into debug.vim

Move debug mapping functions into debug.vim and change their names
appropriately. No functional changes were made.

##### debug: unmap debug mappings in restoreMappings()

2020-10-12 16:31 UTC, kernel-panic96 commented on autoload/go/debug.vim
> +    call s:configureMappings('(go-debug-breakpint)', '(go-debug-continue)', '(go-debug-halt)', '(go-debug-next)', '(go-debug-print)', '(go-debug-step)')
typo in go-debug-breakpoint

2020-10-12 18:09 UTC, bhcleek commented on autoload/go/debug.vim
> +    call s:configureMappings('(go-debug-breakpint)', '(go-debug-continue)', '(go-debug-halt)', '(go-debug-next)', '(go-debug-print)', '(go-debug-step)')
good catch.

2020-10-13 01:48 UTC, bhcleek commented
I've fixed the typo you identified and also pushed some additional fixes and tests.

Do you have any feedback before I push to your branch?

2020-10-13 10:06 UTC, kernel-panic96 commented
I'll try it out tonight

On Tue, Oct 13, 2020, 4:48 AM Billie Cleek <notifications@github.com> wrote:

> I've fixed the typo you identified and also pushed some additional fixes
> and tests.
>
> Do you have any feedback before I push to your branch?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/kernel-panic96/vim-go/pull/1#issuecomment-707433752>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEH2LTTBPQWFQXSZ6YXPNPDSKOWV3ANCNFSM4SMG6KTA>
> .
>

2020-10-13 20:23 UTC, kernel-panic96 commented
Currently the right hand sides are restricted to only vim-go's <Plug> commands. Is this intentional?
I think there's some merit to allowing arbitrary user commands. For example I had `q` mapped to `:GoDebugStop<CR>` which would not be possible in this version.


Also the restoring of mappings does not work for me now. I'm using neovim v0.4.3 (1 minor ver behind latest). `maparg` does not exist in it. Are the tests passing?

2020-10-13 20:32 UTC, kernel-panic96 commented on autoload/go/debug_test.vim
> +    let g:go_debug_mappings = {'(go-debug-continue)': ['q', '<nowait>']}
This `['q', '<nowait>']` could be a little confusing. What do you think about reversing the order `['<nowait>', 'q']` the lhs being last.

2020-10-13 20:56 UTC, kernel-panic96 commented
I think I found the problem, if there wasn't a previous mapping for a given lhs, we have to `unmap` it explicitly.

The test I'm trying to perform is:

Make sure a mapping isn't set for `c` previously in the vimrc.

config:
```
let g:go_debug_mappings = {
    \ '(go-debug-continue)': ['c'],
    \ '(go-debug-halt)': ['q'],
    \ '(go-debug-next)': ['n'],
    \ '(go-debug-step)': ['s'],
\}
```
file under test:
```
package main
// file: main.go

import (
	"fmt"
)

func main() {
	fmt.Println("vim-go")
	fmt.Println("vim-go")
}
```

1. vim main.go +GoDebugStart
2. go to line 8 (first Println)
3. `c` 
4. Expect the debugger continues and breaks at line 8
5. `:GoDebugStop`
6. go to whichever word
7. `ciw` - expect to change the word under the cursor (vim's builtin behavior of `c`. Thus asserting that the mapping has been restored

Can you reproduce it?

2020-10-13 21:00 UTC, bhcleek commented on autoload/go/debug_test.vim
> +    let g:go_debug_mappings = {'(go-debug-continue)': ['q', '<nowait>']}
I'd prefer to keep it as-is. The docs clearly explain the order and how they're to be used. I could support using a dictionary instead of a list for the value, though. WDYT?

2020-10-13 21:07 UTC, bhcleek commented
> Currently the right hand sides are restricted to only vim-go's commands. Is this intentional?
I think there's some merit to allowing arbitrary user commands. For example I had q mapped to :GoDebugStop<CR> which would not be possible in this version.

Yes, this is intentional. I'm certainly open to hooking up a map for `(go-debug-stop)` , though. Ideally, I'd prefer to do that in a follow-on PR to avoid polluting this with a new feature.

2020-10-13 21:11 UTC, kernel-panic96 commented
> I think I found the problem, if there wasn't a previous mapping for a given lhs, we have to unmap it explicitly.

That's not it. It has something to do with the way that restoring works. I tried mapping continue to something I had mapped already and after stopping I had somehow two mappings for the key combination.
```
:map tn
n  tn           @<Plug>(go-debug-continue)
n  tn          * :tabnew<CR>
```
Before the debugger started:
```
:map tn
n  tn          * :tabnew<CR>
```

2020-10-13 21:17 UTC, kernel-panic96 commented
```
let g:go_debug_mappings = {
    \ '(go-debug-continue)': ['c', '<nowait>'],
\}
```
Doesn't seem to work.

2020-10-13 21:20 UTC, kernel-panic96 commented on doc/vim-go.txt
> +can be empty to prevent a key mapping from being applied for one of the named
That's a good feature. +1

2020-10-13 21:30 UTC, bhcleek commented on autoload/go/debug_test.vim
> +    let g:go_debug_mappings = {'(go-debug-continue)': ['q', '<nowait>']}
yeah, I can work with that. I'll add that tonight.

2020-10-13 21:31 UTC, bhcleek commented
Thanks for testing.

I'll look into why you're ending up with a left over `<Plug>(go-debug-continue)` mapping tonight.

as well as to why this config wasn't working for you:
```
let g:go_debug_mappings = {
    \ '(go-debug-continue)': ['c', '<nowait>'],
\}
```

When you say it's not working, what exactly do you mean? Based on tests (i.e. `Test_GoDebugModeRemapsAndRestoresKeys`), it sure seems like it should work. 🤔

2020-10-13 22:01 UTC, kernel-panic96 commented
It's getting late for me. I'll investigate it further tomorrow but here's a [quick screencast](https://vimeo.com/467925918) if it's of any use.

2020-10-13 22:10 UTC, kernel-panic96 commented
For some reason
```
let g:go_debug_mappings = {
    \ '(go-debug-continue)': ['<nowait>', 'c'],
\}
```
works as expected. I'm doing very much black box testing atm, I'll walk these scenarios through the code tomorrow.

2020-10-14 01:04 UTC, bhcleek commented
I can't duplicate the problems you're describing. I used a mapping that already exists, and I'm back to the original state after stopping debugging.

It's also very perculiar that it's only working for you when you reverse the list. 🤔 

I did notice that if I try mapping `c`, then for `(go-debug-continue)` that I get strange errors that I don't get with other keys. I wonder if there's something else in Vim getting in the way somehow 🤔   Try another, less important key (preferably one that isn't an operator key).

I was able to find at least one case where keys aren't unmapped as I'd expect; I'll try to fix that later this evening.

2020-10-14 01:08 UTC, bhcleek commented
Are you sure you don't have `tn` mapped to `<Plug>(go-debug-continue)`  as a buffer-local mapping? I ask, because in the example you provided, its flagged as not remappable, but vim-go doesn't map the keys for debugging as noremappable.

2020-10-14 01:53 UTC, bhcleek commented
Ok, I think I know why your `tn` mapping persisted, or at least I'm close to knowing.

2020-10-14 05:00 UTC, bhcleek commented
PTAL

I made the g:go_debug_mappings dictionary's entry have have dictionary values as we discussed to make it easier to understand and updated docs accordingly.

I also discovered why your `tn` mapping wasn't being fully restored and rectified that.

I'm not able to make `c` map to `<Plug>(go-debug-continue)` successfully; it always results in errors similar to yours when I try to use it.

2020-10-14 19:29 UTC, kernel-panic96 commented on autoload/go/debug.vim
> +      let l:mapping = printf('%s <Plug>%s', l:mapping, l:arg)
This should be like so:
```
      let l:mapping = 'autocmd FileType go nmap <buffer>'
      if has_key(l:config, 'arguments')
        let l:mapping = printf('%s %s', l:mapping, l:config.arguments)
      endif
      let l:mapping = printf('%s %s <Plug>%s', l:mapping, l:lhs, l:arg)
```

In order to handle the arguments correctly. 
In the current version the result in the end is:
`autocmd FileType go nmap <buffer> c <nowait> <Plug>(go-debug-continue)`
the `<nowait>` part should be before the left hand side

2020-10-14 19:31 UTC, bhcleek commented on autoload/go/debug.vim
> +      let l:mapping = printf('%s <Plug>%s', l:mapping, l:arg)
ah, good catch!

2020-10-14 19:34 UTC, kernel-panic96 requested changes

2020-10-14 19:34 UTC, kernel-panic96 commented on autoload/go/debug.vim
> +      let l:mapping = printf('%s <Plug>%s', l:mapping, l:arg)
This should be like so:
```
      let l:mapping = 'autocmd FileType go nmap <buffer>'
      if has_key(l:config, 'arguments')
        let l:mapping = printf('%s %s', l:mapping, l:config.arguments)
      endif
      let l:mapping = printf('%s %s <Plug>%s', l:mapping, l:lhs, l:arg)
```

In order to handle the arguments correctly. 
In the current version the result in the end is:
`autocmd FileType go nmap <buffer> c <nowait> <Plug>(go-debug-continue)`
the `<nowait>` part should be before the left hand side

2020-10-14 19:40 UTC, bhcleek commented on autoload/go/debug.vim
> +      let l:mapping = printf('%s <Plug>%s', l:mapping, l:arg)
good catch

2020-10-14 19:42 UTC, kernel-panic96 commented
I found another failing scenario that I managed to hit myself when trying to implement the buffer local stuff.
The restoration works as longs as you are in the same buffer. The failing scenario is:
1. Start the debugger
2. Break on the first Println
3. Step into it so you change the buffer
4. continue or quit
5. `ctrl + O` to return to the main.go buffer
6. `:map c` shows that 'c' is still mapped to go-debug-continue

I had an idea how to tackle this but it's different than the current approach. So I'll take a look at the code and try to come up with an idea to handle without rewriting the PR.

The idea was ditching the buffer local stuff and doing the mapping not directly to a command but wrapping it first in a function that checks whether the current filetype is go and if that's the case execute whatever was trying to get executed, if not execute the user's original mapping if any.

2020-10-14 19:52 UTC, bhcleek commented
You're right about that bug. However, that's orthogonal to these changes, because that bug exists on master already. I have a PR nearly ready that builds on top of these to address it in a follow-on PR after all of this is merged to master.

2020-10-14 20:17 UTC, kernel-panic96 commented
Would you like me to cover these scenarios with tests? I have some ideas with `:set timeoutlen` for the `<nowait>` attribute. The buffer restoration bug could be tested too I believe.

2020-10-14 21:30 UTC, bhcleek commented
If you're ok with it, I propose that I push these changes to your branch, I'll merge the whole thing, and then we can work on adding some tests separately if you want. Sound good to you?

2020-10-14 21:53 UTC, kernel-panic96 commented
Yeah, sounds good

2020-10-14 21:58 UTC, kernel-panic96 approved these changes

2020-10-15 02:42 UTC, merged